apiVersion: dataset.baizeai.io/v1alpha1
kind: Dataset
metadata:
  name: deepseek-r1-distill-qwen-32b
spec:
  dataSyncRound: 1
  share: true
  source:
    options:
      repoType: MODEL
    type: MODEL_SCOPE
    uri: modelscope://deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
  volumeClaimTemplate:
    metadata: {}
    spec:
      resources: {}
      storageClassName: juicefs-sc-no-share-sc # 可以指定 sc
    status: {}
