apiVersion: dataset.baizeai.io/v1alpha1
kind: Dataset
metadata:
  name: deepseek-r1-distill-qwen-1-5b
  namespace: demo-lws
spec:
  dataSyncRound: 1
  share: true
  source:
    options:
      repoType: MODEL
    type: MODEL_SCOPE
    uri: modelscope://deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  volumeClaimTemplate:
    metadata: {}
    spec:
      resources: {}
      storageClassName: juicefs-sc-no-share-sc
    status: {}

