apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmcache-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmcache-server
  template:
    metadata:
      labels:
        app: lmcache-server
    spec:
      containers:
        - name: lmcache
          image: docker.1ms.run/lmcache/vllm-openai:2025-04-18
          command: ["python3", "-m", "lmcache.experimental.server", "0.0.0.0", "8100"]
          ports:
            - containerPort: 8100
          resources: {}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: lmcache-server
spec:
  selector:
    app: lmcache-server
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: ClusterIP
